import { useQuery } from "react-query";
import { getPopularMovies } from "@/pages/api/rq-tmdb";
import Layout from "@/components/layout/Layout";
import Head from "next/head";

const PopularMovies = () => {
  const { isLoading, isError, data, error } = useQuery(
    "popularMovies",
    () => getPopularMovies(1)
  );

  if (isLoading) return <div>Loading...</div>;
  if (isError) return <>Error: {error}</>


  return (

    <>
    <Layout>
          <Head>
            <title>Demo</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className='bg-gray-800 min-h-screen'>
            <div className="py-10 ">
                <div className="flex flex-col justify-center items-center mx-auto w-5/6">
                    <h1 className="text-white font-bold text-4xl pb-5">Popular Movies</h1>
                    <div className="flex flex-wrap gap-8">
                        {data.results.map((movie: any) => (
                        <div key={movie.id} className='bg-gray-200 rounded-lg p-5'>
                            <p className="text-red-500">{movie.title}</p>
                        </div>
                        ))}
                    </div>
                </div>
            </div>
          </main>
      </Layout>
  </>
  );
};

export default PopularMovies;
