import Head from 'next/head'
import Layout from '@/components/layout/Layout'
import Poster from '@/components/shared/Poster'

export default function MoviesPage() {
  return (
    <>
      <Layout>
            <Head>
              <title>Demo</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='min-h-screen bg-gray-700'>
                <div className='flex flex-col justify-center items-center'>
                    <p className='text-white font-bold text-4xl py-5'>Popular Movies</p>
                    <Poster
                        link='#'
                        poster_path='/poster.jpg'
                        title='Wakanda Forever'
                        release_date='12-06-2023'
                        overview='Lorem20'
                    />
                </div>
            </main>
        </Layout>
    </>
  )
}
